name: Discord Notifications

on:
  pull_request:
    types: [opened, reopened, ready_for_review, closed]
  workflow_run:
    workflows: ["CI/CD Pipeline"] # Nombre del workflow
    types: [completed]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Notify Development Channel (Pull Requests)
        if: github.event_name == 'pull_request'
        uses: appleboy/discord-action@v1.2.0
        with:
