name: Discord Notifications

on:
  pull_request:
    types: [opened, reopened, ready_for_review, closed]
  workflow_run:
    types: [completed]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Development Channel (Pull Requests)
        if: github.event_name == 'pull_request'
        uses: appleboy/discord-action@v1.2.0
        with:
          webhook_url: ${{ secrets.URL_DESARROLLO_DISCORD }}
          message: |
            **Nuevo Evento en Pull Request**
            - **Acción**: ${{ github.event.action }}
            - **Repositorio**: ${{ github.repository }}
            - [Ver PR](${{ github.event.pull_request.html_url }})
            - **Autor**: ${{ github.actor }}

      - name: Notify Tests Channel (Workflows)
        if: github.event_name == 'workflow_run'
        uses: appleboy/discord-action@v1.2.0
        with:
          webhook_url: ${{ secrets.URL_PRUEBAS_DISCORD }}
          message: |
            **Resultado de Workflow**
            - **Workflow**: ${{ github.event.workflow_run.name }}
            - **Estado**: ${{ github.event.workflow_run.conclusion }}
            - **Repositorio**: ${{ github.repository }}
            - [Ver Detalles](${{ github.event.workflow_run.html_url }})
            - **Ejecutado por**: ${{ github.actor }}

      - name: Notify General Channel (Opcional)
        if: github.event_name == 'pull_request' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion != 'skipped')
        uses: appleboy/discord-action@v1.2.0
        with:
          webhook_url: ${{ secrets.DISCORD_GENERAL_WEBHOOK }}
          message: "¡Hola equipo! Se ha realizado una nueva acción en el repositorio." 