# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  push:
    branches: 
      - '*'

  pull_request:
    branches: [ "develop" ]
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

# Runs a single command using the runner's shell
      - name: Send commit message to Discord
        if: github.event_name == 'push'
        uses: appleboy/discord-action@v1.2.0
        with:
          webhook_url: ${{secrets.URL_DISCORD_COMMIT}}
          message: "Nuevo commit: ${{ github.event.head_commit.message }} de ${{github.actor}} en la rama ${{github.ref}}"
      

      - name: Send push message to Discord
        if: github.event_name == 'push'
        uses: appleboy/discord-action@v1.2.0
        with:
          webhook_url: ${{secrets.URL_DISCORD_PUSH}}
          message: "Nuevo push de ${{github.actor}} en la rama ${{github.ref}}"


      - name: Send pull request message to Discord
        if: github.event_name == 'pull_request'
        uses: appleboy/discord-action@v1.2.0
        with:
          webhook_url: ${{secrets.URL_DISCORD_PULL_REQUEST}}
          message: "Nueva pull request de ${{github.actor}} en la rama ${{github.ref}} hacia ${{github.event.pull_request.base.ref}}"
      


